// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 是提供給 Wails 前端呼叫的 Chroma Key 服務
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * 讀取指定圖片，從四個角落取樣，回傳平均背景色
 * 
 * 參數：
 *   - inputPath：來源圖片的本機檔案路徑
 *   - sampleSize：每個角落取樣區塊的邊長，單位為像素
 * 
 * 回傳：
 *   - ColorResult：包含平均背景色的 R、G、B 與 Hex 欄位
 *   - error：開檔或圖片解碼失敗時回傳錯誤
 */
export function CornerColorFromFile(inputPath: string, sampleSize: number): $CancellablePromise<$models.ColorResult> {
    return $Call.ByID(1573750956, inputPath, sampleSize);
}

/**
 * 對來源圖片執行 Chroma Key 去背，並輸出透明背景 PNG
 * 
 * 參數：
 *   - inputPath：來源圖片的本機檔案路徑
 *   - outputPath：處理完成後的透明 PNG 輸出路徑
 *   - p：Chroma Key 的去背參數
 * 
 * 回傳：
 *   - nil：去背成功，PNG 已寫入 outputPath
 *   - error：若來源檔不存在、無法解碼、輸出路徑無法建立或 PNG 寫入失敗
 */
export function ProcessFile(inputPath: string, outputPath: string, p: $models.KeyParams): $CancellablePromise<void> {
    return $Call.ByID(1848954629, inputPath, outputPath, p);
}
