// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CornerColorFromFile：提供 Wails / Svelte 呼叫。
 * inputPath 必須是本機檔案系統的絕對路徑。
 */
export function CornerColorFromFile(inputPath: string, sampleSize: number): $CancellablePromise<$models.ColorResult> {
    return $Call.ByID(1573750956, inputPath, sampleSize);
}

/**
 * ProcessFile：提供 Wails / Svelte 呼叫。
 * p 需要是公開、可 JSON 序列化的 KeyParams。
 */
export function ProcessFile(inputPath: string, outputPath: string, p: $models.KeyParams): $CancellablePromise<void> {
    return $Call.ByID(1848954629, inputPath, outputPath, p);
}
