// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 表示從圖片背景取樣後得到的顏色資訊
 * 
 * 例如前端收到的資料會是： {"r":0,"g":255,"b":0,"hex":"#00FF00"}
 */
export interface ColorResult {
    /**
     * R 是紅色（Red）通道值，範圍為 0 到 255
     */
    "r": number;

    /**
     * G 是綠色（Green）通道值，範圍為 0 到 255
     */
    "g": number;

    /**
     * B 是藍色（Blue）通道值，範圍為 0 到 255
     */
    "b": number;

    /**
     * Hex 是方便前端顯示與 CSS 使用的十六進位色碼
     */
    "hex": string;
}

/**
 * 定義 Chroma Key 去背演算法的輸入參數
 * 
 * 例如前端傳來的 JSON 可能是： {"keyR":0,"keyG":255,"keyB":0,"tolerance":16,"softness":32}
 */
export interface KeyParams {
    /**
     * KeyR 是要移除的 Key Color 的紅色（Red）通道值
     */
    "keyR": number;

    /**
     * KeyG 是要移除的 Key Color 的綠色（Green）通道值
     */
    "keyG": number;

    /**
     * KeyB 是要移除的 Key Color 的藍色（Blue）通道值
     */
    "keyB": number;

    /**
     * Tolerance 是顏色容差, 數值越大，可去除的顏色範圍越廣，但也越可能誤刪前景中相似的顏色
     */
    "tolerance": number;

    /**
     * Softness 是邊緣柔化範圍。數值越大，邊緣透明過渡越柔和，但也可能造成主體邊緣看起來較透明
     */
    "softness": number;
}
