// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ColorResult {
    "r": number;
    "g": number;
    "b": number;
    "hex": string;
}

export interface KeyParams {
    "keyR": number;
    "keyG": number;
    "keyB": number;
    "tolerance": number;
    "softness": number;
}
